### ISSUE TITLE
"TypeError: node.debug is not a function"

### ISSUE THREAD

**Issue by pepit084** [IBM/node-red-contrib-db2-for-i#10]
Environment:
IBM i: V7R3M0
NodeJs: v10.15.0 
Node-Red: v1.2.2

After installing Version 0.2.1 i get error message
`TypeError: node.debug is not a function`

Could someone check this if it is only an issue on my side. 

Thank you!

**Comment by bmarolleau** [comment]
Hello,
I tried to reproduce the issue with approx the same environment: 
IBM i 7.3 , node.js v10.**22.1** , Node-Red **v1.2.5**  and db2fori node v0.2.1 :  test OK
The issue seems related to node, and the node-red , or there's a syntax issue in your flows (javascript code in a function node?) 
1/ Can you try with a simple flow on Node-RED to check if node-red is OK ?  no javascript, just a debug node and db2 node...
2/ Can you try to deploy a sample app on node.js ( for example:  https://github.com/IBM/ibmi-oss-examples/tree/master/nodejs/mynodeapp ) to see if node.js is OK.

Keep us posted.
