### ISSUE TITLE
Install on Mac?

### ISSUE THREAD

**Issue by JonFP** [IBM/node-red-contrib-db2-for-i#8]
I have this running on my IBM i but would like to use it from node-red on my Mac.  When I try to install it fails and the resulting message makes it look as if it is not happy with the OS. Is there a simple way to fix this or is the intent that it only be used locally?

**Comment by bmarolleau** [comment]
Hello @JonFP , 
The node-red-contrib-db2-for-i node uses a native Db2 for i driver, and so can only run on IBM i : install will indeed fail on other operating systems because of unsatisfied dependencies.
Our plan is to propose an alternative ODBC based node , more portable , in the future, so your request helps a lot.  
I hope this answers your question: IBM i local only for now. 
In the meantime, an alternative (acceptable?) is to use a chroot (IFS) jail on IBM i , so you can get your own node-red instance with your nodes & packages isolated from the system wide install.  This is what I use when I propose sandboxes to customers on my IBM i .  This is well explained by Jesse in this [article](https://ibmsystemsmag.com/Power-Systems/07/2019/getting-started-ifs-containers).

**Comment by markirish** [comment]
Hey guys!

Mark Irish here, IBMer and main maintainer for the `odbc` package. I saw this message last week and it got my wheels spinning. I have reached out to the holder of `node-red-contrib-odbc` and he gave me access to publish to that name. I will try to throw something together using the latest `odbc` package, at which point the NodeRED node should be ready to use!

**Comment by JonFP** [comment]
That would be fabulous Mark - thanks.


Jon Paris

jon.f.paris@gmail.com

**Comment by bmarolleau** [comment]
Hi Mark, Jon, 

That sounds great!  and certainly smarter than writing our own db2 for i + ODBC node :) 
Same node on every platform including IBM i 👍  
I'm looking forward to seeing that. thanks.

**Comment by bmarolleau** [comment]
Hi @JonFP , 
It seems that @markdirish did the job , and an alternative to the native `node-red-contrib-db2-for-i ` node (only works on IBM i)  is the portable odbc node  `node-red-contrib-odbc`:  that you find here : 
https://flows.nodered.org/node/@ais_automation/node-red-contrib-odbc

I'm closing the ticket, let me know if any issues. thanks.
